FORMAT: 1A

# CyberCAPTOR server API Open Specification

This is the Open Specification of the REST API of **CyberCAPTOR server**.
**CyberCAPTOR server** is the Java Server of [FIWARE Cyber seCurity Attack graPh moniTORing](https://github.com/fiware-cybercaptor/cybercaptor-server).
**CyberCAPTOR** implements the FIWARE CyberSecurity Generic Enabler.

# Group REST API without inititialization
This group of REST calls contains the API calls that **do not need** the `/initialize` call that loads the vulnerability and remediation database and generates the attack graph and the attack paths.

## Group Version [/rest/version]
Get REST API version information. Generally useful to test that the installation is working.

### Version [GET /rest/version]
Get the simple version of the API.

+ Response 200 (text/plain)

        4.4

### VersionDetailed [GET /rest/version/detailed]
Get the API version in JSON.

+ Response 200 (application/json)
    + Body

            {"version":"4.4"}

## Group Configuration [/rest/json/configuration]
This group contains the calls related to the configuration (remediation cost parameters...).

### Get global remediation cost parameters [GET /rest/json/configuration/remediation-cost-parameters/global]
Get the global remediation cost parameters.

+ Response 200 (application/json)
    + Body

            {"global_parameters":{}}

### Set global remediation cost parameters [POST /rest/json/configuration/remediation-cost-parameters/global]
Set the global remediation cost parameters.

+ Request (application/json)

        {"global_parameters":{"expensesForIT":15000}}

+ Response 200 (application/json)

        {}

### Get snort rule remediation cost parameters [GET /rest/json/configuration/remediation-cost-parameters/snort-rule]
Get the operational cost parameters for a snort rule.

+ Response 200 (application/json)
    + Body

            {"operational_cost_parameters":{}}

### Set snort rule remediation cost parameters [POST /rest/json/configuration/remediation-cost-parameters/snort-rule]
Set the operational cost parameters for a snort rule.

+ Request (application/json)

        {"operational_cost_parameters":{"computationPowerCost":12,"skillRateMaintenance":1,"restartDuration":0.2,"usedStorage":1,"storageCost":5,"skillRateTests":0.7,"deploymentDuration":0.5,"businessApplicationsTestsDuration":4,"maintenanceDuration":10,"remediationCost":10,"remediationUninstallDuration":0.5,"usedPower":1,"serviceUnavailabilityDeploymentDuration":0,"skillRateDeployment":2,"workCost":20,"restartCost":0}}

+ Response 200 (application/json)

        {}

### Get firewall rule remediation cost parameters [GET /rest/json/configuration/remediation-cost-parameters/firewall-rule]
Get the operational cost parameters for a firewall rule.

+ Response 200 (application/json)
    + Body

            {"operational_cost_parameters":{}}

### Set firewall rule remediation cost parameters [POST /rest/json/configuration/remediation-cost-parameters/firewall-rule]
Set the operational cost parameters for a firewall rule.

+ Request (application/json)

        {"operational_cost_parameters":{"computationPowerCost":12,"skillRateMaintenance":1,"restartDuration":0.5,"usedStorage":0,"storageCost":10,"skillRateTests":1,"deploymentDuration":0.5,"businessApplicationsTestsDuration":6,"maintenanceDuration":0,"remediationCost":0,"remediationUninstallDuration":0.1,"usedPower":0.1,"serviceUnavailabilityDeploymentDuration":0,"skillRateDeployment":1.2,"workCost":20,"restartCost":10}}

+ Response 200 (application/json)

        {}

### Get patch remediation cost parameters [GET /rest/json/configuration/remediation-cost-parameters/patch]
Get the operational cost parameters for a patch.

+ Response 200 (application/json)
    + Body

            {"operational_cost_parameters":{}}

### Set patch remediation cost parameters [POST /rest/json/configuration/remediation-cost-parameters/patch]
Set the operational cost parameters for a patch.

+ Request (application/json)

        {"operational_cost_parameters":{"computationPowerCost":5,"skillRateMaintenance":1,"restartDuration":0.5,"usedStorage":0,"storageCost":3,"skillRateTests":0.7,"deploymentDuration":3,"businessApplicationsTestsDuration":4,"maintenanceDuration":0.5,"remediationCost":5,"remediationUninstallDuration":1,"usedPower":0,"serviceUnavailabilityDeploymentDuration":0.5,"skillRateDeployment":1.5,"workCost":20,"restartCost":10}}

+ Response 200 (application/json)

        {}

## Group IDMEF
REST API calls related to IDMEF alerts. See https://www.ietf.org/rfc/rfc4765.txt for more IDMEF alerts information.

### Add IDMEF alerts [POST /rest/json/idmef/add]
From an XML IDMEF file containing alerts.

+ Request (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <idmef:IDMEF-Message xmlns:idmef="http://iana.org/idmef" version="1.0">
          <idmef:Alert messageid="abc123456789">
            <idmef:Analyzer analyzerid="bc-sensor01">
              <idmef:Node category="dns">
                <idmef:name>sensor.example.com</idmef:name>
              </idmef:Node>
            </idmef:Analyzer>
            <idmef:CreateTime ntpstamp="0xbc71f4f5.0xef449129">2000-03-09T10:01:25.93464Z</idmef:CreateTime>
            <idmef:Source ident="a1a2" spoofed="yes">
              <idmef:Node ident="a1a2-1">
                <idmef:Address ident="a1a2-2" category="ipv4-addr">
                  <idmef:address>192.0.2.200</idmef:address>
                </idmef:Address>
              </idmef:Node>
            </idmef:Source>
            <idmef:Target ident="b3b4">
              <idmef:Node>
                <idmef:Address ident="b3b4-1" category="ipv4-addr">
                  <idmef:address>192.0.2.50</idmef:address>
                </idmef:Address>
              </idmef:Node>
            </idmef:Target>
            <idmef:Target ident="c5c6">
              <idmef:Node ident="c5c6-1" category="nisplus">
                <idmef:name>lollipop</idmef:name>
              </idmef:Node>
            </idmef:Target>
            <idmef:Target ident="d7d8">
              <idmef:Node ident="d7d8-1">
                <idmef:location>Cabinet B10</idmef:location>
                <idmef:name>Cisco.router.b10</idmef:name>
              </idmef:Node>
            </idmef:Target>
            <idmef:Classification text="Ping-of-death detected">
              <idmef:Reference origin="cve">
                <idmef:name>CVE-1999-128</idmef:name>
                <idmef:url>http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-1999-128</idmef:url>
              </idmef:Reference>
            </idmef:Classification>
          </idmef:Alert>
        </idmef:IDMEF-Message>

+ Response 200 (application/json)

        {"success":"IDMEF alerts added successfully"}

# Group REST API after initialization
This group contains thte API calls **after** the `/initialize` call that loads the vulnerability and remediation database and generates the attack graph and the attack paths.

## Initialize [/rest/json/initialize]
Generates the attack graph and initializes the main objects needed by other API calls (database, attack graph, attack paths,...).

### Initialize from data on disk [GET]
From the data on disk (.csv inputs files and Nessus vulnerability scan)

+ Response 200 (application/json)

        {"status":"Loaded"}

### Initialize from XML topology [POST]
From an XML topology file containing all information about network topology, firewalling, routing configuration, vulnerabilities...
See https://github.com/fiware-cybercaptor/cybercaptor-data-extraction/blob/master/doc/topology-file-specifications.md for more information.

+ Request (application/xml)

        <topology>
        <machine>
        <name>linux-user-1</name>
        <security_requirement>7</security_requirement>
        <interfaces>
        <interface>
        <name>eth0</name>
        <ipaddress>192.168.1.111</ipaddress>
        <vlan>
        <name>user-lan</name>
        <label>user-lan</label>
        </vlan>
        </interface>
        </interfaces>
        <routes>
        <route>
        <destination>0.0.0.0</destination>
        <mask>0.0.0.0</mask>
        <gateway>192.168.1.111</gateway>
        <interface>eth0</interface>
        </route>
        </routes>
        </machine>
        <machine>
        <name>linux-user-2</name>
        <security_requirement>30</security_requirement>
        <interfaces>
        <interface>
        <name>eth0</name>
        <ipaddress>192.168.1.112</ipaddress>
        <vlan>
        <name>user-lan</name>
        <label>user-lan</label>
        </vlan>
        </interface>
        </interfaces>
        <services>
        <service>
        <name>mdns</name>
        <ipaddress>192.168.1.112</ipaddress>
        <protocol>udp</protocol>
        <port>5353</port>
        <vulnerabilities>
        <vulnerability>
        <type>remoteExploit</type>
        <cve>CVE-2007-2446</cve>
        <goal>privEscalation</goal>
        <cvss>10.0</cvss>
        </vulnerability>
        </vulnerabilities>
        </service>
        </services>
        <routes>
        <route>
        <destination>0.0.0.0</destination>
        <mask>0.0.0.0</mask>
        <gateway>192.168.1.111</gateway>
        <interface>eth0</interface>
        </route>
        </routes>
        </machine>
        </topology>

+ Response 200 (application/json)

        {"status":"Loaded"}

## Group Get the XML topology [/rest/json/topology]
Get the XML topology (for example, this can be used to backup the topology, and to load it again with /initialize)

### Get XML topology [GET]
Get the XML topology for backup

+ Response 200 (application/xml)

    + Headers

            Content-Length: 2174

    + Body

            <topology>
              <machine>
                <name>linux-user-1</name>
                <cpe>cpe:/</cpe>
                <interfaces>
                  <interface>
                    <name>eth0</name>
                    <vlan>
                      <name>user-lan</name>
                      <label>user-lan</label>
                    </vlan>
                    <ipaddress>192.168.1.111</ipaddress>
                    <directly-connected>
                      <ipaddress>192.168.1.112</ipaddress>
                    </directly-connected>
                  </interface>
                </interfaces>
                <services />
                <routes>
                  <route>
                    <destination>0.0.0.0</destination>
                    <mask>0.0.0.0</mask>
                    <gateway>192.168.1.111</gateway>
                    <interface>eth0</interface>
                  </route>
                </routes>
                <input-firewall>
                  <default-policy>ACCEPT</default-policy>
                </input-firewall>
                <output-firewall>
                  <default-policy>ACCEPT</default-policy>
                </output-firewall>
              </machine>
              <machine>
                <name>linux-user-2</name>
                <cpe>cpe:/</cpe>
                <interfaces>
                  <interface>
                    <name>eth0</name>
                    <vlan>
                      <name>user-lan</name>
                      <label>user-lan</label>
                    </vlan>
                    <ipaddress>192.168.1.112</ipaddress>
                    <directly-connected>
                      <ipaddress>192.168.1.111</ipaddress>
                    </directly-connected>
                  </interface>
                </interfaces>
                <services>
                  <service>
                    <name>mdns</name>
                    <ipaddress>192.168.1.112</ipaddress>
                    <protocol>TCP</protocol>
                    <port>5353</port>
                    <CPE>cpe:/</CPE>
                    <vulnerabilities>
                      <vulnerability>
                        <type>remoteExploit</type>
                        <goal>privEscalation</goal>
                        <cve>CVE-2007-2446</cve>
                      </vulnerability>
                    </vulnerabilities>
                  </service>
                </services>
                <routes>
                  <route>
                    <destination>0.0.0.0</destination>
                    <mask>0.0.0.0</mask>
                    <gateway>192.168.1.111</gateway>
                    <interface>eth0</interface>
                  </route>
                </routes>
                <input-firewall>
                  <default-policy>ACCEPT</default-policy>
                </input-firewall>
                <output-firewall>
                  <default-policy>ACCEPT</default-policy>
                </output-firewall>
              </machine>
            </topology>



## Group Hosts [/rest/json/host/list]
This group contains the calls related to hosts, after initialization.

### Get the host list [GET]
Get the list of hosts with their security requirements.

+ Response 200 (application/json)

        {"hosts":[]}

### Set the host list [POST]
Set the hosts and their security_requirements.

+ Request (application/json)

        {"hosts":[{"security_requirements":[{"metric":"High","name":"sec-req-xml"}],"name":"linux-user-1"},{"security_requirements":[{"metric":"High","name":"sec-req-xml"}],"name":"linux-user-2"}]}

+ Response 200 (application/json)

        {}

## Group Attack graphs [/rest/json/attack_graph]
This group contains the calls related to the attack graph, after initialization.

### Get the attack graph [GET]
Get the whole attack graph.

+ Response 200 (application/json)

        {"attack_graph":{"arcs":{},"vertices":{}}}

### Get the attack graph score [GET /rest/json/attack_graph/score]
Get the attack graph score.

+ Response 200 (application/json)

        {"score":""}

### Get the topological attack graph [GET /rest/json/attack_graph/topological]
Get the attack graph in its topological form.

+ Response 200 (application/json)

        {"arcs":{}, "vertices":{}}

## Group Attack paths [/rest/json/attack_path]
This group contains the calls related to the attack paths, after initialization.

### Get the attack paths list [GET /rest/json/attack_path/list]
Get the list of attack paths.

+ Response 200 (application/json)

        {"attack_paths":{}}

### Get the number of attack paths [GET /rest/json/attack_path/number]
Get the total number of attack paths.

+ Response 200 (application/json)

        {"number":2}

### Get one attack path [GET /rest/json/attack_path/{id}]
Get the attack path {id}.

+ Parameters
    + id: 0 (number, required) - The number of attack path to get

+ Response 200 (application/json)
    + Attributes (object)
        + id: 0
    + Body

            {"attack_path":{}}

### Get one attack path in topological form [GET /rest/json/attack_path/{id}/topological]
Get the attack path {id} as a topological graph.

+ Parameters
    + id: 0 (number, required) - The number of attack path to get in topological form

+ Response 200 (application/json)
    + Attributes (object)
        + id: 0
    + Body

            {"arcs":{}, "vertices":{}}

### Get the remediations to an attack path [GET /rest/json/attack_path/{id}/remediations]
Get the remediations of the attack path {id}.

+ Parameters
    + id: 0 (number, required) - The number of the attack path for which remediations will be calculated

+ Response 200 (application/json)
    + Attributes (object)
        + id: 0
    + Body

            {"remediations":{}}

### Simulate the remediation to an attack path [GET /rest/json/attack_path/{id}/remediation/{id_remediation}]
Simulate the remediation {id_remediation} of the path {id}, and compute the new attack graph.

+ Parameters
    + id: 0 (number, required) - The number of the attack path for which remediations will be calculated
    + id_remediation: 0 (number, required) - The number of the remediation to apply.

+ Response 200 (application/json)
    + Attributes (object)
        + id: 0
        + id_remediation: 0
    + Body

            {"attack_graph":{"arcs":{},"vertices":{}}

### Validate the remediation to an attack path [GET /rest/json/attack_path/{id}/remediation/{id_remediation}/validate]
Validate that the remediation {id_remediation} of the path {id} has been applied.

+ Parameters
    + id: 0 (number, required) - The number of the attack path for which remediations will be calculated
    + id_remediation: 0 (number, required) - The number of the remediation to validate.

+ Response 200 (application/json)
    + Attributes (object)
        + id: 0
        + id_remediation: 0
    + Body

            {"success":"The remediation has been validated."}

## Get IDMEF alerts [GET /rest/json/idmef/alerts]
Get the IDMEF alerts that have been received by the server, and not yet sent to this client,
and their potential dynamic remediations that could prevent the described attack.

+ Response 200 (application/json)
    + Body

            {"alerts":[]}
